apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-example
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app4=mmmarceleza/app4
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argo-cd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/app4.update-strategy: latest
    argocd-image-updater.argoproj.io/app4.allow-tags: regexp: ^[a-f0-9]{7}-[0-9]{14}$
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: clusters/hml/apps/simple-example/
    repoURL: "https://github.com/mmmarceleza/argocd"
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
