apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argo-cd
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: 3.2.5
    helm:
      releaseName: kyverno
      values: |
        config:
          webhooks:
            - namespaceSelector:
                matchExpressions:
                  - key: kubernetes.io/metadata.name
                    operator: NotIn
                    values:
                      - kube-system
                      - kyverno
                      - argo-cd
        admissionController:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - infra
                weight: 1
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/component
                        operator: In
                        values:
                          - admission-controller
                  topologyKey: kubernetes.io/hostname
                weight: 1
          replicas: 3
          serviceMonitor:
            enabled: false
          tolerations:
            - key: dedicated
              value: infra
              effect: NoSchedule
        backgroundController:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - infra
                weight: 1
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/component
                        operator: In
                        values:
                          - background-controller
                  topologyKey: kubernetes.io/hostname
                weight: 1
          replicas: 2
          resources: {}
          serviceMonitor:
            enabled: false
          tolerations:
            - key: dedicated
              value: infra
              effect: NoSchedule
        cleanupController:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - infra
                weight: 1
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/component
                        operator: In
                        values:
                          - cleanup-controller
                  topologyKey: kubernetes.io/hostname
                weight: 1
          replicas: 2
          resources: {}
          serviceMonitor:
            enabled: false
          tolerations:
            - key: dedicated
              value: infra
              effect: NoSchedule
        reportsController:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - infra
                weight: 1
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/component
                        operator: In
                        values:
                          - reports-controller
                  topologyKey: kubernetes.io/hostname
                weight: 1
          replicas: 2
          resources: {}
          serviceMonitor:
            enabled: false
          tolerations:
            - key: dedicated
              value: infra
              effect: NoSchedule
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
