apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-hml
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/hml
    repoURL: https://github.com/mmmarceleza/arogcd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
